---
- hosts: all
  # vars:
  #   http_port: 80
  #   max_clients: 200
  # remote_user: yourname
  sudo: yes
  tasks:
    - name: replace package mirror
      command: sed -i -e "s/archive.ubuntu.com/ubuntutym.u-toyama.ac.jp/g" /etc/apt/sources.list
    - name: apt update
      apt: update_cache=yes
    - name: install nginx
      apt: pkg=nginx state=present
    - name: install uwsgi
      apt: pkg=uwsgi state=present
    - name: install supervisor
      apt: pkg=supervisor state=present
    - name: install mysql
      apt: pkg=mysql-server-5.6 state=present force=yes
    - command: /bin/true
      notify: restart mysql
    - name: install redis
      apt: pkg=redis-server state=present
  handlers:
    - name: restart mysql
      service: name=mysql state=restarted
  #   - name: ensure apache is at the latest version
  #     yum: pkg=httpd state=latest
  #   - name: write the apache config file
  #     template: src=/srv/httpd.j2 dest=/etc/httpd.conf
  #     notify:
  #   - restart apache
  #   - name: ensure apache is running (and enable it at boot)
  #     service: name=httpd state=started enabled=yes
  # handlers:
  #   - name: restart apache
  #     service: name=httpd state=restarted
